// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Dependency
	Config
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Dependency struct {
	Pkg              *string `protobuf:"bytes,1,req,name=pkg" json:"pkg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Dependency) Reset()                    { *m = Dependency{} }
func (m *Dependency) String() string            { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()               {}
func (*Dependency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Dependency) GetPkg() string {
	if m != nil && m.Pkg != nil {
		return *m.Pkg
	}
	return ""
}

type Config struct {
	User             *string       `protobuf:"bytes,1,req,name=User,json=user,def=user" json:"User,omitempty"`
	AppName          *string       `protobuf:"bytes,2,req,name=AppName,json=appName,def=app" json:"AppName,omitempty"`
	Deps             []*Dependency `protobuf:"bytes,3,rep,name=deps" json:"deps,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_Config_User string = "user"
const Default_Config_AppName string = "app"

func (m *Config) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return Default_Config_User
}

func (m *Config) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return Default_Config_AppName
}

func (m *Config) GetDeps() []*Dependency {
	if m != nil {
		return m.Deps
	}
	return nil
}

func init() {
	proto.RegisterType((*Dependency)(nil), "main.Dependency")
	proto.RegisterType((*Config)(nil), "main.Config")
}

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x92,
	0xe3, 0xe2, 0x72, 0x49, 0x2d, 0x48, 0xcd, 0x4b, 0x49, 0xcd, 0x4b, 0xae, 0x14, 0x12, 0xe0, 0x62,
	0x2e, 0xc8, 0x4e, 0x97, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0xd2, 0xb9, 0xd8,
	0x9c, 0xc1, 0xba, 0x84, 0x24, 0xb8, 0x58, 0x42, 0x8b, 0x53, 0x8b, 0x20, 0x92, 0x56, 0x2c, 0xa5,
	0x40, 0x76, 0x10, 0x98, 0x14, 0x92, 0xe5, 0x62, 0x77, 0x2c, 0x28, 0xf0, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x02, 0x4b, 0x32, 0x27, 0x16, 0x14, 0x04, 0xb1, 0x27, 0x42, 0xc4, 0x84, 0x54, 0xb8, 0x58,
	0x52, 0x52, 0x0b, 0x8a, 0x25, 0x98, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x04, 0xf4, 0x40, 0xf6, 0xea,
	0x21, 0x2c, 0x0d, 0x02, 0xcb, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff, 0x19, 0x3e, 0xe4, 0x75, 0x9d,
	0x00, 0x00, 0x00,
}
